/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 public/models/Balloon.glb -o src/components/Balloon.jsx -r public
Balloon by Poly by Google [CC-BY] (https://creativecommons.org/licenses/by/3.0/) via Poly Pizza (https://poly.pizza/m/d1gDDhM7pTf)
*/

// import { useGLTF } from "@react-three/drei";
import React from "react";

export function Balloon(props) {
  // const { nodes, materials } = useGLTF("/models/Balloon.glb");
  return (
    <group {...props} dispose={null}>
        <mesh>  
          <boxGeometry />
          <meshStandardMaterial />
        </mesh>
    </group>
  );
}

// useGLTF.preload("/models/Balloon.glb");
